CREATE TABLE enrollments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL UNIQUE,
    program_id BIGINT NOT NULL UNIQUE,
    enrollments_status VARCHAR NOT NULL CHECK ( enrollments_status IN ('active', 'pending', 'cancelled', 'completed')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (program_id) REFERENCES programs(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    enrollments_id BIGINT NOT NULL ,
    payment_amount INTEGER NOT NULL ,
    payment_status VARCHAR NOT NULL CHECK ( payment_status IN ('pending', 'paid', 'failed', 'refunded')),
    payment_date TIMESTAMP DEFAULT  CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (enrollments_id) REFERENCES Enrollments(id)
);

CREATE TABLE programCompletions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL UNIQUE,
    program_id BIGINT NOT NULL UNIQUE,
    program_status VARCHAR CHECK (program_status IN ('active', 'completed', 'pending', 'cancelled')),
    start_program TIMESTAMP,
    end_program TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (program_id) REFERENCES programs(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE certificates(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL ,
    program_id BIGINT NOT NULL ,
    url VARCHAR,
    issue_certificate TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (program_id) REFERENCES programs(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE quizzes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    lesson_id BIGINT NOT NULL ,
    name VARCHAR NOT NULL ,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lesson_id) REFERENCES  lessons(id)
);

CREATE TABLE exercises (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    lesson_id BIGINT NOT NULL ,
    name VARCHAR NOT NULL ,
    url VARCHAR NOT NULL ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lesson_id) REFERENCES  lessons(id)
);

CREATE TABLE discussions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    lesson_id BIGINT NOT NULL,
    content TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lesson_id) REFERENCES lessons(id)
);

CREATE TABLE blogs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    users_id BIGINT NOT NULL ,
    title VARCHAR,
    content TEXT,
    status VARCHAR NOT NULL CHECK ( status IN ('created', 'in moderation', 'published', 'archived') ),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (users_id) REFERENCES users(id)
);