CREATE TABLE courses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL ,
    description text,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE lessons (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL ,
    content text,
    video_url varchar,
    position int ,
    course_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(id)
);

CREATE TABLE modules (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    description text,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE programs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    price int,
    program_type varchar,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);


CREATE TABLE course_modules (
    module_id BIGINT NOT NULL ,
    course_id BIGINT NOT NULL ,
    PRIMARY KEY (module_id, course_id),
    FOREIGN KEY (course_id) REFERENCES courses(id),
    FOREIGN KEY (module_id) REFERENCES modules(id)
);



CREATE TABLE program_modules (
    module_id BIGINT NOT NULL ,
    program_id BIGINT NOT NULL ,
    PRIMARY KEY (program_id, module_id),
    FOREIGN KEY (module_id) REFERENCES modules(id),
    FOREIGN KEY (program_id) REFERENCES programs(id)
);

CREATE TABLE teaching_groups (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL ,
    email VARCHAR NOT NULL UNIQUE ,
    password_hash VARCHAR ,
    teaching_group_id BIGINT,
    role VARCHAR NOT NULL CHECK (role IN ('Student', 'Teacher', 'Admin')),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (teaching_group_id) REFERENCES teaching_groups(id)
);

CREATE TABLE enrollments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    status VARCHAR NOT NULL CHECK (status IN ('active', 'pending', 'cancelled', 'completed')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (program_id) REFERENCES programs(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    enrollment_id BIGINT NOT NULL ,
    amount INTEGER NOT NULL ,
    status VARCHAR NOT NULL CHECK ( status IN ('pending', 'paid', 'failed', 'refunded')),
    paid_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (enrollment_id) REFERENCES Enrollments(id)
);

CREATE TABLE program_completions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    status VARCHAR CHECK (status IN ('active', 'completed', 'pending', 'cancelled')),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (program_id) REFERENCES programs(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE certificates(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL ,
    program_id BIGINT NOT NULL ,
    url VARCHAR,
    issued_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (program_id) REFERENCES programs(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE quizzes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    lesson_id BIGINT NOT NULL ,
    name VARCHAR NOT NULL ,
    content JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lesson_id) REFERENCES  lessons(id)
);

CREATE TABLE exercises (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    lesson_id BIGINT NOT NULL ,
    name VARCHAR NOT NULL ,
    url VARCHAR NOT NULL ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lesson_id) REFERENCES  lessons(id)
);

CREATE TABLE discussions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    lesson_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL ,
    text JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lesson_id) REFERENCES lessons(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE blogs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL ,
    name VARCHAR,
    content TEXT,
    status VARCHAR NOT NULL CHECK ( status IN ('created', 'in moderation', 'published', 'archived') ),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);