CREATE TABLE courses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL ,
    description text,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE lessons (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL ,
    content text,
    video_url varchar,
    position int NOT NULL ,
    course_id BIGINT NOT NULL ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(id)
);

CREATE TABLE modules (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    description text,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE programs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    price int,
    program_type varchar,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE modules_courses (
    module_id BIGINT NOT NULL ,
    course_id BIGINT NOT NULL ,
    PRIMARY KEY (module_id, course_id),
    FOREIGN KEY (course_id) REFERENCES courses(id),
    FOREIGN KEY (module_id) REFERENCES modules(id)
);

CREATE TABLE programs_modules (
    module_id BIGINT NOT NULL ,
    program_id BIGINT NOT NULL ,
    PRIMARY KEY (program_id, module_id),
    FOREIGN KEY (module_id) REFERENCES modules(id),
    FOREIGN KEY (program_id) REFERENCES programs(id)
);

CREATE TABLE teaching_groups (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL ,
    email VARCHAR NOT NULL UNIQUE ,
    password_hash VARCHAR NOT NULL ,
    teaching_group_id BIGINT NOT NULL,
    role VARCHAR NOT NULL CHECK (role IN ('student', 'teacher', 'admin')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (teaching_group_id) REFERENCES teaching_groups(id)
);